apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-ml   
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1   
      maxSurge: 1         
  selector:
    matchLabels:
      app: fastapi-ml   
  template:
    metadata:
      labels:
        app: fastapi-ml   
        component: inference-api
        version: week8
        track: dev
    spec:
      containers:
        - name: fastapi-ml   
          image: fastapi-ml-example:week8  
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_URI
              value: "file:///app/deployment_mlruns/served_model"
            - name: MODEL_STAGE
              value: "staging"
            - name: APP_VERSION
              value: "week8"
            - name: RELEASE_TRACK
              value: "dev"
            - name: MODEL_PATH
              value: "/app/models/lr_model.joblib"
            - name: IMAGE_TAG
              value: "dev"
            - name: MODEL_VERSION
              value: "dev"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
              
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3