apiVersion: v1
kind: Service
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
    component: inference-api
spec:
  type: ClusterIP
  selector:
    app: fastapi-ml
    component: inference-api
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000