apiVersion: v1
kind: Service
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
    component: inference-api
    #track: stable
spec:
  type: ClusterIP
  #type: NodePort
  selector:
    app: fastapi-ml
    component: inference-api
    #track: stable
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000
      #nodePort: 30007   # 可以指定（范围 30000-32767）