apiVersion: v1
kind: Service
metadata:
  name: fastapi-ml-stable
spec:
  type: ClusterIP
  selector:
    app: fastapi-ml
    component: inference-api
    track: stable
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000