version: "3"

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-ml
    volumes:
      - .:/app
    environment:
      - MODEL_URI=${MODEL_URI}
      - MODEL_STAGE=${MODEL_STAGE}
      - APP_VERSION=${APP_VERSION}
      - MODEL_PATH=/app/models/lr_model.joblib
      - RELEASE_TRACK=${RELEASE_TRACK} 
      - IMAGE_TAG=${IMAGE_TAG}
      - MODEL_VERSION=${MODEL_VERSION}
    ports:
      - "8000:8000"
    networks:
      - network
      
  trainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python3 training/training.py

networks:
    network: {}